// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (c) 2026 DeMoD LLC.
//
// Compiles the datagram gate: custos/custos.gen.c (generated by Exsecutor's
// exsc, see custos/PROVENANCE.md) and custos/shim.c (its one import).
fn main() {
    println!("cargo:rerun-if-changed=custos/custos.gen.c");
    println!("cargo:rerun-if-changed=custos/shim.c");
    cc::Build::new()
        .file("custos/custos.gen.c")
        .file("custos/shim.c")
        .std("c11")
        // The emitted prologue refuses -ffast-math with an #error (Exsecutor
        // spec 5.4); say so rather than inherit whatever CFLAGS carry.
        .flag_if_supported("-fno-fast-math")
        // Every unit carries the whole helper set; unused ones are expected.
        .flag_if_supported("-Wno-unused-function")
        .compile("custos");
}
