// SPDX-License-Identifier: LGPL-3.0-only
// Read the wasm-pack output and emit src/wasm/wasm-inline.ts with the wasm
// bytes base64-encoded, so vite-plugin-singlefile can fold everything (JS, CSS,
// and the wasm) into one self-contained index.html.
import { readFileSync, writeFileSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const here = fileURLToPath(new URL('.', import.meta.url))
const wasmPath = new URL('../src/wasm/dcf_codec_wasm_bg.wasm', import.meta.url)
const outPath = new URL('../src/wasm/wasm-inline.ts', import.meta.url)

// wasm-pack drops sidecars into the out dir; a `.gitignore` containing `*` would
// shadow our committed stubs, so prune them — the wasm + glue are gitignored.
for (const f of ['.gitignore', 'package.json', 'README.md'])
  rmSync(new URL(`../src/wasm/${f}`, import.meta.url), { force: true })

const bytes = readFileSync(wasmPath)
const b64 = bytes.toString('base64')
writeFileSync(
  outPath,
  `// SPDX-License-Identifier: LGPL-3.0-only\n` +
    `// GENERATED by scripts/inline-wasm.mjs — base64 of dcf_codec_wasm_bg.wasm.\n` +
    `export const WASM_B64 = '${b64}'\n`,
)
console.error(`inlined ${bytes.length} wasm bytes → ${fileURLToPath(outPath).replace(here, '')}`)
