# SPDX-License-Identifier: LGPL-3.0-only
"""Executable laws + golden-vector generator for the DCF SuperPack container.

SuperPack is a *container adapter* over the 17-byte DeModFrame quantum: it carries
TWO frames in ONE 32-byte message (34 -> 32 bytes) under a single joint CRC, and
reconstructs both inner frames bit-exact on unpack. Because the unpacked frames are
ordinary valid DeModFrames, the 246-vector wire certificate is untouched — this
generator only pins the *container* framing so every language agrees byte-for-byte.

Latency rationale (why SuperPack is an option worth choosing): when frames are
emitted in pairs, SuperPack puts the pair on the wire as a SINGLE datagram instead
of two — one packet, one IP/UDP header, one syscall — so paired traffic crosses the
network with strictly lower per-pair overhead and latency than two separate frames.

Usage:  python3 gen_superpack_vectors.py [superpack_vectors.json]
  Writes  <path>                          (Documentation copy)
  and     <dir>/superpack_vectors.gen.h   (dependency-free C test header)
Exit 0 iff every law holds. Commit identical copies to Documentation/ and python/MCP/.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wirelab_core import encode, decode, crc16_ccitt, FRAME_LEN
from superpack import pack, unpack, is_superpack, SUPER_TYPE, SUPER_LEN, CORE_LEN

ok = lambda name: print(f"  PASS  {name}")


# ── A representative, deterministic set of frame pairs ────────────────────────
# (frame_type, seq, src, dst, payload, ts_us)
_FRAMES = [
    (0, 0x0000, 0x0000, 0x0000, b"\x00\x00\x00\x00", 0x000000),
    (3, 0x1234, 0x0001, 0xFFFF, b"\xde\xad\xbe\xef", 0xAB12CD),
    (0, 0x0102, 0x0304, 0x0506, b"\xca\xfe\xba\xbe", 0x010203),
    (1, 0x7FFF, 0xA1A1, 0x00B2, b"ping", 0x0000FF),
    (2, 0x00A0, 0x1000, 0x2000, b"\xff\x00\xff\x00", 0xFFFFFF),
    (3, 0xFFFF, 0xFFFF, 0xFFFF, b"\xff\xff\xff\xff", 0xFFFFFF),
]


def _mk(t):
    return encode(t[0], t[1], t[2], t[3], t[4], t[5])


# Pair them up: (0,1), (2,3), (4,5), plus a couple of cross pairs and a self-pair.
pair_idx = [(0, 1), (2, 3), (4, 5), (1, 4), (3, 2), (5, 5), (0, 5)]

cases = []
for ai, bi in pair_idx:
    a = _mk(_FRAMES[ai])
    b = _mk(_FRAMES[bi])
    sp = pack(a, b)

    # Law 1: container is exactly 32 bytes, strictly smaller than two raw frames.
    assert len(sp) == SUPER_LEN == 32 < 2 * FRAME_LEN
    # Law 2: it is recognisably a SuperPack (sync + version/type tag).
    assert is_superpack(sp)
    # Law 3: round-trip is lossless and each output is a valid DeModFrame.
    ra, rb = unpack(sp)
    assert (ra, rb) == (a, b), "SuperPack is not lossless"
    decode(ra); decode(rb)
    # Law 4: the joint CRC covers both quanta (any single-bit flip is rejected).
    for i in range(SUPER_LEN):
        bad = bytearray(sp); bad[i] ^= 0x01
        try:
            unpack(bytes(bad))
            raise AssertionError(f"tamper at byte {i} not detected")
        except ValueError:
            pass

    cases.append({"a": a.hex(), "b": b.hex(), "super": sp.hex()})

ok(f"{len(cases)} SuperPack pairs: 34->32 bytes, lossless, joint-CRC, tamper-evident")

# ── Pinned anchors ────────────────────────────────────────────────────────────
zero = encode(0, 0, 0, 0, b"\x00\x00\x00\x00", 0)
zero_joint = int.from_bytes(pack(zero, zero)[30:32], "big")
assert zero_joint == 0x5B75, f"golden joint CRC drift: 0x{zero_joint:04X}"
assert crc16_ccitt(b"123456789") == 0x29B1
assert crc16_ccitt(bytes(15)) == 0x4EC3
ok("anchors: inner CRC(123456789)=0x29B1, CRC(0^15)=0x4EC3, zero-core joint=0x5B75")

cert = {
    "super_type": SUPER_TYPE,
    "super_len": SUPER_LEN,
    "core_len": CORE_LEN,
    "anchors": {
        "crc_123456789": 0x29B1,
        "crc_zero15": 0x4EC3,
        "zero_core_joint_crc": 0x5B75,
    },
    "cases": cases,
}

out = sys.argv[1] if len(sys.argv) > 1 else "superpack_vectors.json"
with open(out, "w") as f:
    json.dump(cert, f, indent=1)
    f.write("\n")
print(f"  INFO  wrote {out} ({os.path.getsize(out)} bytes, {len(cases)} cases)")


# ── Dependency-free C header (mirrors codec/*_vectors.gen.h) ───────────────────
def carr(hexstr):
    return "{" + ",".join(f"0x{hexstr[i:i+2].upper()}" for i in range(0, len(hexstr), 2)) + "}"


hdr_path = os.path.join(os.path.dirname(os.path.abspath(out)), "superpack_vectors.gen.h")
with open(hdr_path, "w") as h:
    h.write("/* GENERATED by python/MCP/gen_superpack_vectors.py — DO NOT EDIT. */\n")
    h.write("#ifndef DCF_SUPERPACK_VECTORS_GEN_H\n#define DCF_SUPERPACK_VECTORS_GEN_H\n")
    h.write("#include <stdint.h>\n\n")
    h.write("#define SP_SUPER_TYPE 0x05\n#define SP_SUPER_LEN 32\n#define SP_CORE_LEN 14\n")
    h.write("#define SP_ZERO_CORE_JOINT_CRC 0x5B75u\n\n")
    h.write("typedef struct { uint8_t a[17], b[17], super[32]; } sp_case_t;\n")
    h.write("static const sp_case_t SP_CASES[] = {\n")
    for c in cases:
        h.write("  {" + carr(c["a"]) + "," + carr(c["b"]) + "," + carr(c["super"]) + "},\n")
    h.write("};\n")
    h.write("static const int SP_N_CASES = (int)(sizeof(SP_CASES)/sizeof(SP_CASES[0]));\n")
    h.write("#endif\n")
print(f"  INFO  wrote {hdr_path} ({os.path.getsize(hdr_path)} bytes)")
print("ALL SUPERPACK LAWS HOLD")
