# SPDX-License-Identifier: LGPL-3.0-only
"""Executable laws + golden-vector generator for the DCF FEC adapter (Reed-Solomon).

FEC is a *correction* adapter over the 17-byte DeModFrame: a systematic Reed-Solomon
code over GF(2^8) (prim 0x11D, α=2, fcr=0) appends `2t` parity bytes so a lossy
medium (RF/SDR, acoustic) can *recover* a frame, not just detect damage. The frame
and its 246-vector certificate are untouched — FEC wraps frames. This generator pins
the byte-exact ENCODE (deterministic) and the CORRECTION law (decode recovers the
message after <= t byte-errors) so Python/C/Rust agree byte-for-byte.

Usage:  python3 gen_fec_vectors.py [fec_vectors.json]
  Writes  <path>                     (Documentation copy)
  and     <dir>/fec_vectors.gen.h    (dependency-free C test header)
Exit 0 iff every law holds. Commit identical copies to Documentation/ and python/MCP/.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wirelab_core import encode
import feclab_core as fec

NP = fec.RS_DEFAULT_NPARITY            # 2t = 16 -> corrects t = 8
T = NP // 2
ok = lambda name: print(f"  PASS  {name}")

# Representative, deterministic 17-byte frames (mirrors the SuperPack vector set).
_FRAMES = [
    (0, 0x0000, 0x0000, 0x0000, b"\x00\x00\x00\x00", 0x000000),
    (3, 0x1234, 0x0001, 0xFFFF, b"\xde\xad\xbe\xef", 0xAB12CD),
    (0, 0x0102, 0x0304, 0x0506, b"\xca\xfe\xba\xbe", 0x010203),
    (1, 0x7FFF, 0xA1A1, 0x00B2, b"ping", 0x0000FF),
    (2, 0x00A0, 0x1000, 0x2000, b"\xff\x00\xff\x00", 0xFFFFFF),
    (3, 0xFFFF, 0xFFFF, 0xFFFF, b"\xff\xff\xff\xff", 0xFFFFFF),
]
frames = [encode(*t) for t in _FRAMES]

cases = []        # encode determinism: {msg, code}
correct = []      # correction law: {corrupt, msg, nerr}
for idx, f in enumerate(frames):
    code = fec.rs_encode(f, NP)
    # Law 1: systematic — the message passes through unchanged.
    assert code[:len(f)] == f, "RS must be systematic"
    assert len(code) == len(f) + NP
    # Law 2: a clean codeword decodes with zero corrections.
    msg, n = fec.rs_decode(code, NP)
    assert msg == f and n == 0
    cases.append({"msg": f.hex(), "code": code.hex()})

    # Law 3: correct exactly t byte-errors at DETERMINISTIC positions/values.
    bad = bytearray(code)
    positions = [(idx * 3 + k * (len(code) // T)) % len(code) for k in range(T)]
    positions = sorted(set(positions))
    for p in positions:
        bad[p] ^= 0xA5 if (p & 1) else 0x5A
    rec, nc = fec.rs_decode(bytes(bad), NP)
    assert rec == f, f"correction failed for frame {idx}"
    correct.append({"corrupt": bytes(bad).hex(), "msg": f.hex(), "nerr": len(positions)})

ok(f"{len(cases)} frames: systematic encode, clean decode, correct <= {T} byte-errors")

# Law 4: > t errors are not silently accepted (RS fails or residual syndrome).
over = bytearray(fec.rs_encode(frames[1], NP))
for p in range(T + 1):
    over[p * 2] ^= 0x33
try:
    fec.rs_decode(bytes(over), NP)
    # If it "decodes", it must NOT equal the original (would be a silent mis-correct).
    raise AssertionError("t+1 errors silently accepted")
except fec.FecError:
    pass
ok(f"> {T} byte-errors are rejected (caught by RS / frame CRC)")

# Law 5: interleaver round-trips and spreads a depth-length burst.
cws = [fec.rs_encode(f, NP) for f in frames[:5]]
stream = fec.interleave(cws)
recv = fec.deinterleave(stream, len(cws), len(cws[0]))
assert recv == cws, "interleave round-trip"
ok("interleaver round-trips (burst spreading verified in tests)")

# ── Pinned anchors ────────────────────────────────────────────────────────────
gen_poly = bytes(fec.rs_generator_poly(NP))            # 17 coeffs for 2t=16
zero_parity = fec.rs_encode(bytes(17), NP)[17:]        # parity of 17 zero bytes
GEN_POLY_HEX = gen_poly.hex()
ZERO_PARITY_HEX = zero_parity.hex()
print(f"  INFO  gen_poly(2t=16) = {GEN_POLY_HEX}")
print(f"  INFO  zero-frame parity = {ZERO_PARITY_HEX}")

cert = {
    "field_prim": fec.GF_PRIM, "gen": fec.GF_GEN, "fcr": fec.FCR, "nparity": NP,
    "anchors": {"gen_poly": GEN_POLY_HEX, "zero_frame_parity": ZERO_PARITY_HEX},
    "cases": cases,
    "correct": correct,
}

out = sys.argv[1] if len(sys.argv) > 1 else "fec_vectors.json"
with open(out, "w") as f:
    json.dump(cert, f, indent=1)
    f.write("\n")
print(f"  INFO  wrote {out} ({os.path.getsize(out)} bytes, {len(cases)} cases)")


def carr(hexstr):
    return "{" + ",".join(f"0x{hexstr[i:i+2].upper()}" for i in range(0, len(hexstr), 2)) + "}"


hdr = os.path.join(os.path.dirname(os.path.abspath(out)), "fec_vectors.gen.h")
with open(hdr, "w") as h:
    h.write("/* GENERATED by python/MCP/gen_fec_vectors.py — DO NOT EDIT. */\n")
    h.write("#ifndef DCF_FEC_VECTORS_GEN_H\n#define DCF_FEC_VECTORS_GEN_H\n")
    h.write("#include <stdint.h>\n\n")
    h.write(f"#define FEC_NPARITY {NP}\n#define FEC_MSG_LEN 17\n")
    h.write(f"#define FEC_CODE_LEN {17 + NP}\n\n")
    h.write("typedef struct { uint8_t msg[17], code[FEC_CODE_LEN]; } fec_case_t;\n")
    h.write("static const fec_case_t FEC_CASES[] = {\n")
    for c in cases:
        h.write("  {" + carr(c["msg"]) + "," + carr(c["code"]) + "},\n")
    h.write("};\n")
    h.write("static const int FEC_N_CASES = (int)(sizeof(FEC_CASES)/sizeof(FEC_CASES[0]));\n\n")
    h.write("typedef struct { uint8_t corrupt[FEC_CODE_LEN], msg[17]; int nerr; } fec_fix_t;\n")
    h.write("static const fec_fix_t FEC_FIX[] = {\n")
    for c in correct:
        h.write("  {" + carr(c["corrupt"]) + "," + carr(c["msg"]) + f",{c['nerr']}}},\n")
    h.write("};\n")
    h.write("static const int FEC_N_FIX = (int)(sizeof(FEC_FIX)/sizeof(FEC_FIX[0]));\n")
    h.write("#endif\n")
print(f"  INFO  wrote {hdr} ({os.path.getsize(hdr)} bytes)")
print("ALL FEC LAWS HOLD")
