# SPDX-License-Identifier: LGPL-3.0-only
"""Executable laws + golden-vector generator for the DCF modulation mapping.

Pins the byte<->symbol bijection (the certified half of the Faust-DSP modem) for
every modulation, so the C (codec/demod_modulation.h) and Rust (codec/src/modulation.rs)
implementations agree with the Python reference byte-for-byte.

Usage:  python3 gen_modulation_vectors.py [modulation_vectors.json]
Writes  <path>  and  <dir>/modulation_vectors.gen.h. Exit 0 iff every law holds.
Commit identical copies to Documentation/ and python/MCP/.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from modulationlab_core import (
    MOD_FSK, MOD_OOK, MOD_PSK, MOD_QAM, BITS_PER_SYMBOL, MOD_NAMES,
    gray, ungray, modulate, demodulate,
)

ok = lambda name: print(f"  PASS  {name}")

# ── Law: gray is a bijection on 0..255; ungray inverts it ─────────────────────
assert [gray(n) for n in range(8)] == [0, 1, 3, 2, 6, 7, 5, 4]
assert all(ungray(gray(n)) == n for n in range(256))
ok("Gray code is a bijection (ungray∘gray = id on 0..255)")

# Representative byte inputs.
inputs = {
    "example_frame": bytes.fromhex("d31312340001ffffdeadbeefab12cd24c0"),  # 17B golden frame
    "superpack": bytes.fromhex("d31510000000000000000000000000001312340001ffffdeadbeefab12cd2435"),  # 32B
    "short": b"Hi",
    "ramp": bytes(range(20)),
}

cases = []
for mod in (MOD_FSK, MOD_OOK, MOD_PSK, MOD_QAM):
    for name, data in inputs.items():
        syms = modulate(mod, data)
        # Law: lossless round-trip, and every symbol is in range.
        assert demodulate(mod, syms, len(data)) == data, (MOD_NAMES[mod], name)
        assert all(0 <= s < (1 << BITS_PER_SYMBOL[mod]) for s in syms)
        # Law: symbol count = ceil(8*len / bits_per_symbol).
        bps = BITS_PER_SYMBOL[mod]
        assert len(syms) == (8 * len(data) + bps - 1) // bps
        cases.append({"mod": mod, "name": f"{MOD_NAMES[mod]}_{name}",
                      "data": data.hex(), "symbols": syms})
ok(f"{len(cases)} cases: byte→symbol→byte round-trip + symbol-count law (4 modulations)")

cert = {
    "modulations": [{"id": m, "name": MOD_NAMES[m], "bits_per_symbol": BITS_PER_SYMBOL[m]}
                    for m in (MOD_FSK, MOD_OOK, MOD_PSK, MOD_QAM)],
    "gray_anchor": [gray(n) for n in range(16)],
    "cases": cases,
}

out = sys.argv[1] if len(sys.argv) > 1 else "modulation_vectors.json"
with open(out, "w") as f:
    json.dump(cert, f, indent=1)
    f.write("\n")
print(f"  INFO  wrote {out} ({os.path.getsize(out)} bytes, {len(cases)} cases)")

# ── dependency-free C header ──────────────────────────────────────────────────
def carr(vals):
    return "{" + ",".join(str(v) for v in vals) + "}"

hdr = os.path.join(os.path.dirname(os.path.abspath(out)), "modulation_vectors.gen.h")
with open(hdr, "w") as h:
    h.write("/* GENERATED by python/MCP/gen_modulation_vectors.py — DO NOT EDIT. */\n")
    h.write("#ifndef DCF_MODULATION_VECTORS_GEN_H\n#define DCF_MODULATION_VECTORS_GEN_H\n")
    h.write("#include <stdint.h>\n\n")
    h.write("typedef struct { uint8_t mod, bits_per_symbol; uint16_t data_len;\n")
    h.write("  uint8_t data[64]; uint16_t n_syms; uint8_t syms[512]; } mod_case_t;\n")
    h.write("static const mod_case_t MOD_CASES[] = {\n")
    for c in cases:
        data = bytes.fromhex(c["data"])
        syms = c["symbols"]
        h.write("  {%d,%d,%d,%s,%d,%s},\n" % (
            c["mod"], BITS_PER_SYMBOL[c["mod"]], len(data),
            carr(list(data)) if data else "{0}", len(syms), carr(syms) if syms else "{0}"))
    h.write("};\n")
    h.write("static const int MOD_N_CASES = (int)(sizeof(MOD_CASES)/sizeof(MOD_CASES[0]));\n")
    h.write("#endif\n")
print(f"  INFO  wrote {hdr} ({os.path.getsize(hdr)} bytes)")
print("ALL MODULATION LAWS HOLD")
