/* SPDX-License-Identifier: LGPL-3.0-only
 *
 * test_superpack_certify.c — C certification for the DCF SuperPack container.
 *
 * Certifies the C implementation (codec/demod_superpack.h) against the
 * cross-language golden vectors (codec/superpack_vectors.gen.h, generated by
 * gen_superpack_vectors.py). Passing this == byte-agreement with the Python,
 * Rust, and Go references.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec C_SDK/tests/test_superpack_certify.c -o test_sp
 */
#include <stdio.h>
#include <string.h>
#include "demod_superpack.h"
#include "superpack_vectors.gen.h"

static int failures = 0;
static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. pack(A, B) matches the golden 32-byte container ── */
    for (int i = 0; i < SP_N_CASES; i++) {
        const sp_case_t *c = &SP_CASES[i];
        uint8_t out[DCF_SUPER_LEN];
        if (!dcf_superpack_pack(c->a, c->b, out)) { fail("pack returned false", i); continue; }
        if (!dcf_superpack_is(out, DCF_SUPER_LEN)) { fail("not recognised as SuperPack", i); continue; }
        if (memcmp(out, c->super, DCF_SUPER_LEN) != 0) fail("pack bytes mismatch", i);
    }
    printf("PASS: %d SuperPack pairs pack byte-identically\n", SP_N_CASES);

    /* ── 2. unpack(S) reconstructs both frames bit-exact ── */
    for (int i = 0; i < SP_N_CASES; i++) {
        const sp_case_t *c = &SP_CASES[i];
        uint8_t a[DCF_FRAME_SIZE], b[DCF_FRAME_SIZE];
        if (!dcf_superpack_unpack(c->super, a, b)) { fail("unpack returned false", i); continue; }
        if (memcmp(a, c->a, DCF_FRAME_SIZE) != 0) fail("frame A mismatch", i);
        if (memcmp(b, c->b, DCF_FRAME_SIZE) != 0) fail("frame B mismatch", i);
    }
    printf("PASS: %d SuperPack pairs unpack losslessly\n", SP_N_CASES);

    /* ── 3. joint CRC is tamper-evident; zero-core anchor holds ── */
    {
        uint8_t bad[DCF_SUPER_LEN], a[DCF_FRAME_SIZE], b[DCF_FRAME_SIZE];
        for (int i = 0; i < (int)DCF_SUPER_LEN; i++) {
            memcpy(bad, SP_CASES[0].super, DCF_SUPER_LEN);
            bad[i] ^= 0x01;
            if (dcf_superpack_unpack(bad, a, b)) fail("tamper not detected", i);
        }
        /* zero-core frame: sync 0xD3, sflags 0x10, 14 zero bytes, then its CRC. */
        uint8_t zero[DCF_FRAME_SIZE];
        memset(zero, 0, sizeof zero);
        zero[0] = DCF_SYNC_BYTE;
        zero[1] = (uint8_t)(1u << DCF_VERSION_SHIFT);
        uint16_t zcrc = dcf_crc16(zero, DCF_FRAME_CRC_COVER);
        zero[15] = (uint8_t)(zcrc >> 8);
        zero[16] = (uint8_t)zcrc;
        uint8_t spz[DCF_SUPER_LEN];
        if (!dcf_superpack_pack(zero, zero, spz)) fail("pack(zero,zero)", 0);
        uint16_t joint = (uint16_t)((spz[30] << 8) | spz[31]);
        if (joint != SP_ZERO_CORE_JOINT_CRC || joint != 0x5B75u)
            fail("zero-core joint CRC drift", (int)joint);
    }
    printf("PASS: joint CRC tamper-evident; zero-core anchor = 0x5B75\n");

    if (failures) { fprintf(stderr, "\n%d FAILURE(S)\n", failures); return 1; }
    printf("\nALL SUPERPACK VECTORS HOLD — C DCF SuperPack is cemented.\n");
    return 0;
}
