/* test_monitor_certify.c — C certification for the DCF-Cue (cue-plane) L2 framing.
 *
 * Certifies codec/demod_monitor.h against the cross-language golden vectors
 * (codec/monitor_vectors.gen.h, generated by gen_monitor_vectors.py).  Compiled L2-only.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec -o test_monitor_certify \
 *            C_SDK/tests/test_monitor_certify.c -lm
 */
#include <stdio.h>
#include <string.h>
#include "demod_monitor.h"
#include "monitor_vectors.gen.h"

static int failures = 0;
static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. Framing ── */
    for (int i = 0; i < MN_N_FRAMING; i++) {
        const mn_framing_t *c = &MN_FRAMING[i];
        uint8_t frames[130][DCF_FRAME_SIZE];
        size_t n = 0;
        if (!dcf_mon_packetize(c->payload, c->payload_len, c->block_seq, c->ts_us,
                               c->src, c->dst, c->block_samples, c->format, c->channels,
                               c->flags, frames, 130, &n)) {
            fail("packetize returned false", i);
            continue;
        }
        if (n != c->n_frames) { fail("frame count mismatch", i); continue; }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0)
                fail("frame bytes mismatch", i);
    }
    printf("PASS: %d framing cases packetize byte-identically\n", MN_N_FRAMING);

    /* ── 2. Reassembly ── */
    for (int i = 0; i < MN_N_REASM; i++) {
        const mn_reasm_t *c = &MN_REASM[i];
        dcf_mon_reasm_t r;
        dcf_mon_reasm_init(&r);
        int got = 0, ok = 1;
        for (int f = 0; f < c->n_in; f++) {
            dcf_mon_block_t out;
            if (dcf_mon_reasm_push(&r, c->in_frames[f], &out) == DCF_MON_REASM_BLOCK) {
                if (got >= c->n_blk) { ok = 0; break; }
                const mn_block_t *e = &c->blks[got++];
                if (out.block_seq != e->block_seq || out.ts_us != e->ts_us ||
                    out.src != e->src || out.dst != e->dst ||
                    out.block_samples != e->block_samples || out.format != e->format ||
                    out.channels != e->channels || out.flags != e->flags ||
                    out.payload_len != e->payload_len ||
                    memcmp(out.payload, e->payload, out.payload_len) != 0) ok = 0;
            }
        }
        if (got != c->n_blk) ok = 0;
        uint16_t lost[8];
        size_t nlost = dcf_mon_reasm_finalize(&r, lost, 8);
        if ((int)nlost != c->n_lost) ok = 0;
        for (int l = 0; l < c->n_lost; l++)
            if (lost[l] != c->lost[l]) ok = 0;
        if (!ok) fail(c->name, i);
    }
    printf("PASS: %d reassembly cases (reorder/drop/duplicate)\n", MN_N_REASM);

    /* ── 3. Channel anchor ── */
    if (dcf_mon_channel_id("123456789") != 0x29B1) fail("channel_id anchor", 0);
    if (dcf_mon_channel_id("") != 0xFFFF) fail("channel_id empty=broadcast", 0);
    printf("PASS: channel_id rendezvous anchor holds\n");

    if (failures == 0)
        printf("\nALL CUE VECTORS HOLD — C DCF-Cue L2 is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C DCF-Cue L2 is NOT cemented.\n", failures);
    return failures != 0;
}
