/* test_audio_certify.c — C certification for the DCF-Audio L2 framing layer.
 *
 * Certifies the C implementation (codec/demod_audio.h) against the cross-language
 * golden vectors (codec/audio_vectors.gen.h, generated by gen_audio_vectors.py).
 * Compiled L2-only: no libopus, no Faust synthesis needed for the byte layout.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I../../codec -o test_audio_certify test_audio_certify.c
 *   (CI uses -I codec from the repo root.)
 */
#include <stdio.h>
#include <string.h>
#include "demod_audio.h"
#include "audio_vectors.gen.h"

static int failures = 0;

static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. Framing: packetize matches expected frames byte-for-byte ── */
    for (int i = 0; i < AV_N_FRAMING; i++) {
        const av_framing_t *c = &AV_FRAMING[i];
        uint8_t frames[DCF_AUDIO_MAX_FRAMES][DCF_FRAME_SIZE];
        size_t n = 0;
        if (!dcf_audio_packetize(c->codec_id, c->payload, c->payload_len,
                                 c->packet_id, c->ts_us, c->src, c->dst, c->flags,
                                 frames, DCF_AUDIO_MAX_FRAMES, &n)) {
            fail("packetize returned false", i);
            continue;
        }
        if (n != c->n_frames) { fail("frame count mismatch", i); continue; }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0)
                fail("frame bytes mismatch", i);
    }
    printf("PASS: %d framing cases packetize byte-identically\n", AV_N_FRAMING);

    /* ── 2. Reassembly: reorder / drop→lost / duplicate ── */
    for (int i = 0; i < AV_N_REASM; i++) {
        const av_reasm_t *c = &AV_REASM[i];
        dcf_audio_reasm_t r;
        dcf_audio_reasm_init(&r);
        int got = 0, ok = 1;
        for (int f = 0; f < c->n_in; f++) {
            dcf_audio_packet_t out;
            if (dcf_audio_reasm_push(&r, c->in_frames[f], &out) == DCF_REASM_PACKET) {
                if (got >= c->n_pkt) { ok = 0; break; }
                const av_pkt_t *e = &c->pkts[got++];
                if (out.packet_id != e->packet_id || out.ts_us != e->ts_us ||
                    out.codec_id != e->codec_id || out.flags != e->flags ||
                    out.payload_len != e->payload_len ||
                    memcmp(out.payload, e->payload, out.payload_len) != 0) ok = 0;
            }
        }
        if (got != c->n_pkt) ok = 0;
        uint16_t lost[8];
        size_t nlost = dcf_audio_reasm_finalize(&r, lost, 8);
        if ((int)nlost != c->n_lost) ok = 0;
        for (int l = 0; l < c->n_lost; l++)
            if (lost[l] != c->lost[l]) ok = 0;
        if (!ok) fail(c->name, i);
    }
    printf("PASS: %d reassembly cases (reorder/drop/duplicate)\n", AV_N_REASM);

    /* ── 3. PCM-diag decode∘encode is byte-lossless ── */
    for (int i = 0; i < AV_N_PCM; i++) {
        float pcm[DCF_PCM_DIAG_BLOCK];
        uint8_t out[DCF_PCM_DIAG_BLOCK];
        dcf_pcm_diag_decode(AV_PCM[i], DCF_PCM_DIAG_BLOCK, pcm);
        dcf_pcm_diag_encode(pcm, DCF_PCM_DIAG_BLOCK, out);
        if (memcmp(out, AV_PCM[i], DCF_PCM_DIAG_BLOCK) != 0) fail("pcm roundtrip", i);
    }
    printf("PASS: %d PCM-diag blocks decode->encode losslessly\n", AV_N_PCM);

    /* ── 4. PM param pack/unpack round-trip ── */
    for (int i = 0; i < AV_N_PM; i++) {
        const av_pm_t *c = &AV_PM[i];
        dcf_pm_params_t p = {c->f0, c->amp, c->mod_index, c->mod_ratio,
                             c->bright, c->env, c->flags};
        uint8_t b[8];
        dcf_pm_pack(&p, b);
        if (memcmp(b, c->bytes, 8) != 0) fail("pm pack", i);
        dcf_pm_params_t q;
        dcf_pm_unpack(c->bytes, &q);
        if (memcmp(&q, &p, sizeof p) != 0) fail("pm unpack", i);
    }
    printf("PASS: %d PM param blocks pack/unpack identically\n", AV_N_PM);

    /* ── 5. Codec registry sanity ── */
    const dcf_codec_vtable_t *pcm = dcf_codec_get(DCF_CODEC_PCM_DIAG);
    if (!pcm || pcm->sample_rate != DCF_PCM_DIAG_RATE || pcm->block_samples != DCF_PCM_DIAG_BLOCK)
        fail("codec registry pcm-diag", 0);
    printf("PASS: codec registry returns the PCM-diag profile\n");

    if (failures == 0)
        printf("\nALL AUDIO VECTORS HOLD — C DCF-Audio L2 is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C DCF-Audio L2 is NOT cemented.\n", failures);
    return failures != 0;
}
