/* test_sstv_certify.c — C certification for the DCF-SSTV L2 framing layer.
 *
 * Certifies the C implementation (codec/demod_sstv.h) against the cross-language
 * golden vectors (codec/sstv_vectors.gen.h, generated by gen_sstv_vectors.py).
 * Compiled L2-only: no runtime needed for the byte layout.  The dependency-free
 * header bounds payloads to 128 B; the 8188 B rail is certified by Python + Rust.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec -o test_sstv_certify \
 *            C_SDK/tests/test_sstv_certify.c -lm
 */
#include <stdio.h>
#include <string.h>
#include "demod_sstv.h"
#include "sstv_vectors.gen.h"

static int failures = 0;

static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. Framing: packetize matches expected frames byte-for-byte ── */
    for (int i = 0; i < SV_N_FRAMING; i++) {
        const sv_framing_t *c = &SV_FRAMING[i];
        uint8_t frames[64][DCF_FRAME_SIZE];   /* header bounds cases to <=33 frames */
        size_t n = 0;
        if (!dcf_sstv_packetize(c->payload, c->payload_len, c->image_id, c->ts_us,
                                c->src, c->dst, c->format_id, c->flags, frames, 64, &n)) {
            fail("packetize returned false", i);
            continue;
        }
        if (n != c->n_frames) { fail("frame count mismatch", i); continue; }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0)
                fail("frame bytes mismatch", i);
    }
    printf("PASS: %d framing cases packetize byte-identically\n", SV_N_FRAMING);

    /* ── 2. Reassembly: reorder / drop→lost / duplicate ── */
    for (int i = 0; i < SV_N_REASM; i++) {
        const sv_reasm_t *c = &SV_REASM[i];
        dcf_sstv_reasm_t r;
        dcf_sstv_reasm_init(&r);
        int got = 0, ok = 1;
        for (int f = 0; f < c->n_in; f++) {
            dcf_sstv_image_t out;
            if (dcf_sstv_reasm_push(&r, c->in_frames[f], &out) == DCF_SSTV_REASM_IMAGE) {
                if (got >= c->n_img) { ok = 0; break; }
                const sv_img_t *e = &c->imgs[got++];
                if (out.image_id != e->image_id || out.ts_us != e->ts_us ||
                    out.src != e->src || out.dst != e->dst ||
                    out.format_id != e->format_id || out.flags != e->flags ||
                    out.payload_len != e->payload_len ||
                    memcmp(out.payload, e->payload, out.payload_len) != 0) ok = 0;
            }
        }
        if (got != c->n_img) ok = 0;
        uint16_t lost[8];
        size_t nlost = dcf_sstv_reasm_finalize(&r, lost, 8);
        if ((int)nlost != c->n_lost) ok = 0;
        for (int l = 0; l < c->n_lost; l++)
            if (lost[l] != c->lost[l]) ok = 0;
        if (!ok) fail(c->name, i);
    }
    printf("PASS: %d reassembly cases (reorder/drop/duplicate)\n", SV_N_REASM);

    /* ── 3. Channel rendezvous anchor: crc16("123456789") == 0x29B1 ── */
    if (dcf_sstv_channel_id("123456789") != 0x29B1) fail("channel_id anchor", 0);
    if (dcf_sstv_channel_id("") != 0xFFFF) fail("channel_id empty=broadcast", 0);
    printf("PASS: channel_id rendezvous anchor holds\n");

    if (failures == 0)
        printf("\nALL SSTV VECTORS HOLD — C DCF-SSTV L2 is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C DCF-SSTV L2 is NOT cemented.\n", failures);
    return failures != 0;
}
