/* test_wire_certify.c — C SDK wire quantum certification harness.
 *
 * Certifies the C reference codec (codec/demod_frame.h) against the FULL
 * 246-vector certificate — all 109 encode_basis vectors and all 137
 * syndrome_basis vectors — plus the published CRC anchors, the cross-language
 * example frame, and an exhaustive single-bit corruption audit.
 *
 * The vectors come from codec/golden_vectors.gen.h, generated by
 * python/MCP/verify_laws.py from the same Documentation/golden_vectors.json
 * every other language certifies against; CI regenerates and diffs it, so the C
 * codec cannot silently drift from the certificate. (Before this file consumed
 * the vectors it checked anchors only — green, but not actually diffed against
 * the certificate the way every adapter cert is.)
 *
 * Return code 0 = cemented.
 *
 * Build (CI): gcc -std=c11 -Wall -Wextra -I codec -o wire_certify \
 *               C_SDK/tests/test_wire_certify.c -lm
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "../../codec/demod_frame.h"
#include "../../codec/golden_vectors.gen.h"

/* The affine validity syndrome: CRC over bytes[0..14] XOR the carried CRC.
 * Zero iff the word is CRC-valid. Mirrors wirelab_core.syndrome. */
static uint16_t wire_syndrome(const uint8_t *w) {
    return (uint16_t)(dcf_crc16(w, 15) ^ (uint16_t)((w[15] << 8) | w[16]));
}

int main(void) {
    int failures = 0;

    /* ── Anchor checks (the cross-language CRC fixtures) ── */
    uint8_t ascii123456789[] = {0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39};
    uint16_t crc = dcf_crc16(ascii123456789, 9);
    if (crc != 0x29B1) {
        fprintf(stderr, "FAIL: CRC anchor '123456789' = 0x%04X, expected 0x29B1\n", crc);
        failures++;
    } else {
        printf("PASS: CRC anchor '123456789' -> 0x29B1\n");
    }

    uint8_t zero15[15] = {0};
    uint16_t crc_zero = dcf_crc16(zero15, 15);
    if (crc_zero != 0x4EC3) {
        fprintf(stderr, "FAIL: CRC(0^15) = 0x%04X, expected 0x4EC3\n", crc_zero);
        failures++;
    } else {
        printf("PASS: CRC(0^15) -> 0x4EC3\n");
    }

    /* ── Encode the canonical example frame and check it byte-for-byte ── */
    dcf_frame_t fields;
    dcf_frame_init(&fields, /*version*/ 1, DCF_TYPE_DATA,
                   /*seq*/ 0x1234, /*src*/ 0x0001, /*dst*/ 0xFFFF);
    fields.payload[0] = 0xDE; fields.payload[1] = 0xAD;
    fields.payload[2] = 0xBE; fields.payload[3] = 0xEF;
    fields.timestamp_us = 0xAB12CD;

    uint8_t frame[DCF_FRAME_SIZE];
    dcf_frame_encode(&fields, frame);

    const char *expected_hex = "D31012340001FFFFDEADBEEFAB12CDA963";
    char got_hex[2 * DCF_FRAME_SIZE + 1] = {0};
    for (int i = 0; i < (int)DCF_FRAME_SIZE; i++) sprintf(got_hex + 2 * i, "%02X", frame[i]);
    if (strcmp(got_hex, expected_hex) != 0) {  /* both sides are uppercase hex */
        fprintf(stderr, "FAIL: exampleFrame = %s, expected %s\n", got_hex, expected_hex);
        failures++;
    } else {
        printf("PASS: exampleFrame = %s\n", got_hex);
    }

    /* ── Round-trip decode must succeed and recover the fields ── */
    dcf_frame_t decoded;
    if (!dcf_frame_decode(frame, &decoded)) {
        fprintf(stderr, "FAIL: decode of a valid frame returned false\n");
        failures++;
    } else if (decoded.seq != fields.seq || decoded.src_id != fields.src_id ||
               decoded.dst_id != fields.dst_id || decoded.type != fields.type ||
               decoded.timestamp_us != fields.timestamp_us ||
               memcmp(decoded.payload, fields.payload, 4) != 0) {
        fprintf(stderr, "FAIL: decoded fields differ from encoded fields\n");
        failures++;
    } else {
        printf("PASS: encode/decode round-trip preserves all fields\n");
    }

    /* ── Bit-flip audit: all 136 single-bit corruptions rejected ── */
    int accepted = 0;
    for (int bit = 0; bit < (int)DCF_FRAME_SIZE * 8; bit++) {
        uint8_t bad[DCF_FRAME_SIZE];
        memcpy(bad, frame, DCF_FRAME_SIZE);
        bad[bit / 8] ^= (uint8_t)(1u << (7 - bit % 8));
        if (dcf_frame_decode(bad, &decoded)) accepted++;
    }
    if (accepted != 0) {
        fprintf(stderr, "FAIL: %d single-bit corruptions accepted (expected 0)\n", accepted);
        failures++;
    } else {
        printf("PASS: all %d single-bit corruptions rejected\n", (int)DCF_FRAME_SIZE * 8);
    }

    /* ── encode_basis: all 109 vectors must encode byte-for-byte ── */
    int enc_bad = 0;
    for (int i = 0; i < WIRE_ENCODE_N; i++) {
        const wire_encode_t *v = &WIRE_ENCODE[i];
        dcf_frame_t f;
        dcf_frame_init(&f, 1, (dcf_frame_type_t)v->frame_type, v->seq, v->src, v->dst);
        memcpy(f.payload, v->payload, 4);
        f.timestamp_us = v->ts_us;
        uint8_t got[DCF_FRAME_SIZE];
        dcf_frame_encode(&f, got);
        if (memcmp(got, v->frame, DCF_FRAME_SIZE) != 0) {
            if (enc_bad == 0) fprintf(stderr, "FAIL: encode_basis[%d] mismatch\n", i);
            enc_bad++;
        }
    }
    if (enc_bad != 0) {
        fprintf(stderr, "FAIL: %d/%d encode_basis vectors wrong\n", enc_bad, WIRE_ENCODE_N);
        failures++;
    } else {
        printf("PASS: all %d encode_basis vectors byte-identical\n", WIRE_ENCODE_N);
    }

    /* ── syndrome_basis: all 137 words must hash to their recorded syndrome ── */
    int syn_bad = 0;
    for (int i = 0; i < WIRE_SYNDROME_N; i++) {
        const wire_syndrome_t *v = &WIRE_SYNDROME[i];
        uint16_t got = wire_syndrome(v->word);
        if (got != v->syndrome) {
            if (syn_bad == 0)
                fprintf(stderr, "FAIL: syndrome_basis[%d] = 0x%04X, expected 0x%04X\n",
                        i, got, v->syndrome);
            syn_bad++;
        }
    }
    if (syn_bad != 0) {
        fprintf(stderr, "FAIL: %d/%d syndrome_basis vectors wrong\n", syn_bad, WIRE_SYNDROME_N);
        failures++;
    } else {
        printf("PASS: all %d syndrome_basis vectors match\n", WIRE_SYNDROME_N);
    }

    if (failures == 0) {
        printf("\nALL %d VECTORS HOLD — C SDK wire codec is cemented.\n",
               WIRE_ENCODE_N + WIRE_SYNDROME_N);
    } else {
        fprintf(stderr, "\n%d FAILURE(S) — C SDK wire codec is NOT cemented.\n", failures);
    }
    return failures != 0;
}
