/* test_snake_certify.c — C certification for the DCF-Snake record-plane L2 framing,
 * the BEACON grandmaster media clock, and the unwrap_pid timeline primitive.
 *
 * Certifies the C implementation (codec/demod_snake.h) against the cross-language
 * golden vectors (codec/snake_vectors.gen.h, generated by gen_snake_vectors.py).
 * Compiled L2-only: no runtime needed for the byte layout.  The dependency-free
 * header bounds record payloads to 128 B; the QSS-scale packets (784/1328/2048) and
 * the 8188 B rail are certified by Python + Rust.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec -o test_snake_certify \
 *            C_SDK/tests/test_snake_certify.c -lm
 */
#include <stdio.h>
#include <string.h>
#include "demod_snake.h"
#include "snake_vectors.gen.h"

static int failures = 0;

static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. Framing: packetize matches expected frames byte-for-byte (CTRL record) ── */
    for (int i = 0; i < SN_N_FRAMING; i++) {
        const sn_framing_t *c = &SN_FRAMING[i];
        uint8_t frames[64][DCF_FRAME_SIZE];   /* header bounds cases to <=33 frames */
        size_t n = 0;
        if (!dcf_snake_packetize(c->payload, c->payload_len, c->stream_id, c->ts_us,
                                 c->src, c->dst, c->mode_id, c->flags, frames, 64, &n)) {
            fail("packetize returned false", i);
            continue;
        }
        if (n != c->n_frames) { fail("frame count mismatch", i); continue; }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0)
                fail("frame bytes mismatch", i);
    }
    printf("PASS: %d framing cases packetize byte-identically\n", SN_N_FRAMING);

    /* ── 2. Reassembly: reorder / drop→lost / duplicate ── */
    for (int i = 0; i < SN_N_REASM; i++) {
        const sn_reasm_t *c = &SN_REASM[i];
        dcf_snake_reasm_t r;
        dcf_snake_reasm_init(&r, DCF_TYPE_CTRL);
        int got = 0, ok = 1;
        for (int f = 0; f < c->n_in; f++) {
            dcf_snake_msg_t out;
            if (dcf_snake_reasm_push(&r, c->in_frames[f], &out) == DCF_SNAKE_REASM_MESSAGE) {
                if (got >= c->n_msg) { ok = 0; break; }
                const sn_msg_t *e = &c->msgs[got++];
                if (out.stream_id != e->stream_id || out.ts_us != e->ts_us ||
                    out.src != e->src || out.dst != e->dst ||
                    out.mode_id != e->mode_id || out.flags != e->flags ||
                    out.payload_len != e->payload_len ||
                    memcmp(out.payload, e->payload, out.payload_len) != 0) ok = 0;
            }
        }
        if (got != c->n_msg) ok = 0;
        uint16_t lost[8];
        size_t nlost = dcf_snake_reasm_finalize(&r, lost, 8);
        if ((int)nlost != c->n_lost) ok = 0;
        for (int l = 0; l < c->n_lost; l++)
            if (lost[l] != c->lost[l]) ok = 0;
        if (!ok) fail(c->name, i);
    }
    printf("PASS: %d reassembly cases (reorder/drop/duplicate)\n", SN_N_REASM);

    /* ── 3. BEACON clock: pack==payload, packetize==frames, reassemble+unpack==fields ── */
    for (int i = 0; i < SN_N_CLOCK; i++) {
        const sn_clock_t *c = &SN_CLOCK[i];
        dcf_snake_clock_t in = {c->gm_sample_count, c->nominal_rate_mhz, c->tx_seq, c->epoch};
        uint8_t packed[DCF_SNAKE_CLOCK_LEN];
        dcf_snake_pack_clock(&in, packed);
        if (memcmp(packed, c->payload, DCF_SNAKE_CLOCK_LEN) != 0) fail("clock pack bytes", i);

        dcf_snake_clock_t back;
        dcf_snake_unpack_clock(packed, &back);
        if (back.gm_sample_count != in.gm_sample_count || back.nominal_rate_mhz != in.nominal_rate_mhz ||
            back.tx_seq != in.tx_seq || back.epoch != in.epoch) fail("clock unpack roundtrip", i);

        uint8_t frames[8][DCF_FRAME_SIZE];
        size_t n = 0;
        if (!dcf_snake_beacon_packetize(packed, c->beacon_slot, c->ts_us, c->src, c->dst,
                                        0, frames, 8, &n)) { fail("beacon packetize false", i); continue; }
        if (n != c->n_frames) { fail("beacon frame count", i); continue; }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0) fail("beacon frame bytes", i);

        dcf_snake_reasm_t r;
        dcf_snake_reasm_init(&r, DCF_TYPE_BEACON);
        dcf_snake_msg_t out;
        int emitted = 0;
        for (size_t f = 0; f < n; f++)
            if (dcf_snake_reasm_push(&r, frames[f], &out) == DCF_SNAKE_REASM_MESSAGE) emitted = 1;
        if (!emitted || out.payload_len != DCF_SNAKE_CLOCK_LEN ||
            memcmp(out.payload, c->payload, DCF_SNAKE_CLOCK_LEN) != 0 ||
            out.mode_id != DCF_SNAKE_CLOCK_VER) fail("beacon reassemble", i);
    }
    printf("PASS: %d clock cases (pack/unpack + fragmented BEACON framing)\n", SN_N_CLOCK);

    /* ── 4. unwrap_pid: matches sync.rs on forward/rollover/reorder ── */
    for (int i = 0; i < SN_N_UNWRAP; i++) {
        const sn_unwrap_t *u = &SN_UNWRAP[i];
        if (dcf_snake_unwrap_pid(u->prev_abs, u->raw, u->mod) != u->expect)
            fail("unwrap_pid mismatch", i);
    }
    printf("PASS: %d unwrap_pid cases\n", SN_N_UNWRAP);

    /* ── 5. Channel rendezvous anchor: crc16("123456789") == 0x29B1 ── */
    if (dcf_snake_channel_id("123456789") != 0x29B1) fail("channel_id anchor", 0);
    if (dcf_snake_channel_id("") != 0xFFFF) fail("channel_id empty=broadcast", 0);
    printf("PASS: channel_id rendezvous anchor holds\n");

    if (failures == 0)
        printf("\nALL SNAKE VECTORS HOLD — C DCF-Snake L2 + clock + unwrap is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C DCF-Snake L2 is NOT cemented.\n", failures);
    return failures != 0;
}
