/* test_hydrapack_certify.c — C certification for the HydraPack serialization layer.
 *
 * Certifies the C implementation (codec/demod_hydrapack.h) against the cross-language
 * golden vectors (codec/hydrapack_vectors.gen.h, generated by gen_hydrapack_vectors.py).
 * Passing this == byte-agreement with the Rust and Python references.
 *
 * The test:
 *  1. Defines the 6 test schemas inline (matching the Python schemas).
 *  2. Packs test values and compares quanta/buffers bytes to the golden vectors.
 *  3. Round-trip: unpack the golden bytes → re-pack → compare (faithful unpack).
 *  4. Pipe checksum verification (FNV-1a).
 *  5. OpenPipe pack/unpack round-trip.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec -o test_hydrapack_certify \
 *            C_SDK/tests/test_hydrapack_certify.c -lm
 */
#include <stdio.h>
#include <string.h>
#include "demod_hydrapack.h"
#include "hydrapack_vectors.gen.h"

static int failures = 0;
static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

/* ── Test schemas (must match gen_hydrapack_vectors.py SCHEMAS) ──────────── */
static const dcf_hp_field_t sub_pos[] = {{"x",DCF_HP_U,12,NULL,0},{"y",DCF_HP_U,12,NULL,0}};
static const dcf_hp_field_t sub_vel[] = {{"vx",DCF_HP_I,8,NULL,0},{"vy",DCF_HP_I,8,NULL,0}};

static const dcf_hp_field_t f0[] = {
    {"x",DCF_HP_U,10,NULL,0},{"y",DCF_HP_U,10,NULL,0},
    {"v",DCF_HP_I,8,NULL,0},{"hot",DCF_HP_BOOL,0,NULL,0}};
static const dcf_hp_field_t f1[] = {
    {"sensor_type",DCF_HP_U,8,NULL,0},{"value",DCF_HP_I,16,NULL,0},
    {"flags",DCF_HP_U,8,NULL,0}};
static const dcf_hp_field_t f2[] = {
    {"cmd",DCF_HP_ENUM,4,NULL,0},{"mode",DCF_HP_ENUM,4,NULL,0},
    {"param",DCF_HP_I,16,NULL,0},{"seq",DCF_HP_U,8,NULL,0}};
static const dcf_hp_field_t f3[] = {
    {"x",DCF_HP_U,12,NULL,0},{"y",DCF_HP_U,12,NULL,0},
    {"vx",DCF_HP_I,8,NULL,0},{"vy",DCF_HP_I,8,NULL,0},
    {"heading",DCF_HP_U,8,NULL,0},{"flags",DCF_HP_U,8,NULL,0}};
static const dcf_hp_field_t f4[] = {
    {"p0",DCF_HP_U,12,NULL,0},{"p1",DCF_HP_U,12,NULL,0},
    {"p2",DCF_HP_U,12,NULL,0},{"p3",DCF_HP_U,12,NULL,0},
    {"p4",DCF_HP_U,12,NULL,0},{"p5",DCF_HP_U,12,NULL,0},
    {"p6",DCF_HP_U,12,NULL,0},{"p7",DCF_HP_U,12,NULL,0}};
static const dcf_hp_field_t f5[] = {
    {"pos",DCF_HP_STRUCT,0,sub_pos,2},
    {"vel",DCF_HP_STRUCT,0,sub_vel,2},
    {"id",DCF_HP_U,8,NULL,0}};

static const dcf_hp_schema_t schemas[] = {
    {0,1,f0,4}, {1,1,f1,3}, {2,1,f2,4},
    {3,1,f3,6}, {4,1,f4,8}, {5,1,f5,3},
};
#define N_SCHEMAS (int)(sizeof(schemas)/sizeof(schemas[0]))

/* ── Test values (must match gen_hydrapack_vectors.py test_values) ───────── */
/* Schema 0: x=1000 y=700 v=-3 hot=true */
static const dcf_hp_value_t v0 = {{1000,700,-3,0},{1,0,0,0},3};
/* Schema 1: sensor_type=2 value=-32000 flags=0x0F */
static const dcf_hp_value_t v1 = {{2,-32000,15,0},{0,0,0,0},3};
/* Schema 2: cmd=1 mode=2 param=-300 seq=42 */
static const dcf_hp_value_t v2 = {{1,2,-300,42},{0,0,0,0},4};
/* Schema 3: x=3500 y=2800 vx=-12 vy=7 heading=180 flags=0x42 */
static const dcf_hp_value_t v3 = {{3500,2800,-12,7,180,0x42},{0,0,0,0,0,0},6};
/* Schema 4: p0..p7 = 17,117,217,...,717 */
static const dcf_hp_value_t v4 = {{17,117,217,317,417,517,617,717},{0,0,0,0,0,0,0,0},8};
/* Schema 5: pos={3500,2800} vel={-1,2} id=42 */
static const dcf_hp_value_t v5 = {{3500,2800,-1,2,42,0,0,0},{0,0,0,0,0,0,0,0},5};

static const dcf_hp_value_t *test_values[] = {&v0,&v1,&v2,&v3,&v4,&v5};

int main(void) {
    /* ── 1. Single-quantum: pack values → compare quanta bytes ── */
    for (int i = 0; i < HPV_N_QUANTUM_SINGLE; i++) {
        const hpv_quantum_single_t *c = &HPV_QUANTUM_SINGLE[i];
        const dcf_hp_schema_t *s = &schemas[i];
        const dcf_hp_value_t *v = test_values[i];
        uint8_t q[8][DCF_HP_QUANTUM_LEN];
        size_t nq = 0;
        if (!dcf_hp_pack_quantum(s, v, 0, false, q, 8, &nq)) {
            fail("single pack returned false", i); continue;
        }
        if (nq != c->n_quanta) { fail("single: count mismatch", i); continue; }
        for (size_t j = 0; j < nq; j++)
            if (memcmp(q[j], c->quanta[j], DCF_HP_QUANTUM_LEN) != 0)
                fail("single: quantum bytes mismatch", i);
        /* round-trip: unpack → re-pack → compare */
        dcf_hp_value_t out;
        dcf_hp_unpack_quantum_single(q, s, &out);
        uint8_t q2[8][DCF_HP_QUANTUM_LEN];
        size_t nq2 = 0;
        dcf_hp_pack_quantum(s, &out, 0, false, q2, 8, &nq2);
        if (nq2 != nq) { fail("single: round-trip count", i); continue; }
        for (size_t j = 0; j < nq; j++)
            if (memcmp(q2[j], q[j], DCF_HP_QUANTUM_LEN) != 0)
                fail("single: round-trip bytes", i);
    }
    printf("PASS: %d single-quantum cases byte-identical + round-tripped\n",
           HPV_N_QUANTUM_SINGLE);

    /* ── 2. Multi-quantum: pack values → compare quanta bytes ── */
    /* Schema index mapping: single cases use schemas 0,1,2; multi use 3,4,5 */
    const int multi_schema_idx[] = {3, 4, 5};
    for (int i = 0; i < HPV_N_QUANTUM_MULTI; i++) {
        const hpv_quantum_multi_t *c = &HPV_QUANTUM_MULTI[i];
        const dcf_hp_schema_t *s = &schemas[multi_schema_idx[i]];
        const dcf_hp_value_t *v = test_values[multi_schema_idx[i]];
        uint8_t q[8][DCF_HP_QUANTUM_LEN];
        size_t nq = 0;
        if (!dcf_hp_pack_quantum(s, v, c->flags, false, q, 8, &nq)) {
            fail("multi pack returned false", i); continue;
        }
        if (nq != c->n_quanta) { fail("multi: count mismatch", i); continue; }
        for (size_t j = 0; j < nq; j++)
            if (memcmp(q[j], c->quanta[j], DCF_HP_QUANTUM_LEN) != 0)
                fail("multi: quantum bytes mismatch", i);
        /* round-trip */
        dcf_hp_value_t out;
        uint8_t flags;
        if (!dcf_hp_unpack_quantum_multi(q, nq, s, &out, &flags)) {
            fail("multi: unpack returned false", i); continue;
        }
        if (flags != c->flags) { fail("multi: flags mismatch", i); continue; }
        uint8_t q2[8][DCF_HP_QUANTUM_LEN];
        size_t nq2 = 0;
        dcf_hp_pack_quantum(s, &out, c->flags, false, q2, 8, &nq2);
        if (nq2 != nq) { fail("multi: round-trip count", i); continue; }
        for (size_t j = 0; j < nq; j++)
            if (memcmp(q2[j], q[j], DCF_HP_QUANTUM_LEN) != 0)
                fail("multi: round-trip bytes", i);
    }
    printf("PASS: %d multi-quantum cases byte-identical + round-tripped\n",
           HPV_N_QUANTUM_MULTI);

    /* ── 3. Pipe: unpack buffer → re-pack → compare + checksum ── */
    for (int i = 0; i < HPV_N_PIPE; i++) {
        const hpv_pipe_t *c = &HPV_PIPE[i];
        const dcf_hp_schema_t *s = &schemas[multi_schema_idx[i]];
        /* verify checksum */
        uint32_t ck = dcf_pipe_fnv1a32(c->buffer, c->buf_len);
        if (ck != c->checksum) { fail("pipe: checksum mismatch", i); continue; }
        /* round-trip: unpack → re-pack → compare */
        dcf_hp_value_t out;
        dcf_hp_unpack_pipe(s, c->buffer, c->buf_len, &out);
        uint8_t buf[128];
        uint32_t ck2;
        size_t len2 = dcf_hp_pack_pipe(s, &out, buf, sizeof(buf), &ck2);
        if (len2 != c->buf_len) { fail("pipe: round-trip length", i); continue; }
        if (memcmp(buf, c->buffer, c->buf_len) != 0)
            fail("pipe: round-trip bytes", i);
        if (ck2 != c->checksum) fail("pipe: round-trip checksum", i);
    }
    printf("PASS: %d pipe cases checksum-verified + round-tripped\n", HPV_N_PIPE);

    /* ── 4. OpenPipe: pack → compare bytes; unpack → verify fields ── */
    for (int i = 0; i < HPV_N_OPENPIPE; i++) {
        const hpv_openpipe_t *c = &HPV_OPENPIPE[i];
        uint8_t op[DCF_HP_OPENPIPE_LEN];
        dcf_hp_pack_openpipe(op, c->session_id, c->total_len, c->chunk_size,
                             c->checksum, c->schema_id, c->version, c->flags);
        if (memcmp(op, c->bytes, DCF_HP_OPENPIPE_LEN) != 0)
            fail("openpipe: bytes mismatch", i);
        /* unpack and verify */
        uint16_t sid, scid; uint32_t tl, ck; uint16_t cs;
        uint8_t sv, fl;
        if (!dcf_hp_unpack_openpipe(op, DCF_HP_OPENPIPE_LEN, &sid, &tl, &cs, &ck,
                                    &scid, &sv, &fl)) {
            fail("openpipe: unpack returned false", i); continue;
        }
        if (sid != c->session_id || tl != c->total_len || cs != c->chunk_size ||
            ck != c->checksum || scid != c->schema_id || sv != c->version ||
            fl != c->flags)
            fail("openpipe: field mismatch", i);
    }
    printf("PASS: %d openpipe cases byte-identical\n", HPV_N_OPENPIPE);

    /* ── 5. FNV-1a anchors ── */
    if (dcf_pipe_fnv1a32((const uint8_t *)"", 0) != 0x811C9DC5u) fail("FNV empty anchor", 0);
    if (dcf_pipe_fnv1a32((const uint8_t *)"hello", 5) != 0x4F9F2CABu) fail("FNV hello anchor", 0);
    printf("PASS: FNV-1a anchors hold (0x811C9DC5, 0x4F9F2CAB)\n");

    if (failures == 0)
        printf("\nALL HYDRAPACK VECTORS HOLD — C HydraPack is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C HydraPack is NOT cemented.\n", failures);
    return failures != 0;
}