/* test_game_certify.c — C certification for the DCF-Game L2 framing layer.
 *
 * Certifies the C implementation (codec/demod_game.h) against the cross-language
 * golden vectors (codec/game_vectors.gen.h, generated by gen_game_vectors.py).
 * Compiled L2-only: no game runtime needed for the byte layout.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I../../codec -o test_game_certify test_game_certify.c
 *   (CI uses -I codec from the repo root.)
 */
#include <stdio.h>
#include <string.h>
#include "demod_game.h"
#include "game_vectors.gen.h"

static int failures = 0;

static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. Framing: packetize matches expected frames byte-for-byte ── */
    for (int i = 0; i < GV_N_FRAMING; i++) {
        const gv_framing_t *c = &GV_FRAMING[i];
        uint8_t frames[DCF_GAME_MAX_FRAMES][DCF_FRAME_SIZE];
        size_t n = 0;
        if (!dcf_game_packetize(c->msg_type_id, c->payload, c->payload_len,
                                c->packet_id, c->ts_us, c->src, c->dst, c->flags,
                                frames, DCF_GAME_MAX_FRAMES, &n)) {
            fail("packetize returned false", i);
            continue;
        }
        if (n != c->n_frames) { fail("frame count mismatch", i); continue; }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0)
                fail("frame bytes mismatch", i);
    }
    printf("PASS: %d framing cases packetize byte-identically\n", GV_N_FRAMING);

    /* ── 2. Reassembly: reorder / drop→lost / duplicate ── */
    for (int i = 0; i < GV_N_REASM; i++) {
        const gv_reasm_t *c = &GV_REASM[i];
        dcf_game_reasm_t r;
        dcf_game_reasm_init(&r);
        int got = 0, ok = 1;
        for (int f = 0; f < c->n_in; f++) {
            dcf_game_packet_t out;
            if (dcf_game_reasm_push(&r, c->in_frames[f], &out) == DCF_GAME_REASM_PACKET) {
                if (got >= c->n_pkt) { ok = 0; break; }
                const gv_pkt_t *e = &c->pkts[got++];
                if (out.packet_id != e->packet_id || out.ts_us != e->ts_us ||
                    out.msg_type_id != e->msg_type_id || out.flags != e->flags ||
                    out.payload_len != e->payload_len ||
                    memcmp(out.payload, e->payload, out.payload_len) != 0) ok = 0;
            }
        }
        if (got != c->n_pkt) ok = 0;
        uint16_t lost[8];
        size_t nlost = dcf_game_reasm_finalize(&r, lost, 8);
        if ((int)nlost != c->n_lost) ok = 0;
        for (int l = 0; l < c->n_lost; l++)
            if (lost[l] != c->lost[l]) ok = 0;
        if (!ok) fail(c->name, i);
    }
    printf("PASS: %d reassembly cases (reorder/drop/duplicate)\n", GV_N_REASM);

    /* ── 3. SNAPSHOT body pack∘unpack is byte-lossless ── */
    for (int i = 0; i < GV_N_SNAPSHOT; i++) {
        dcf_snapshot_t s;
        uint8_t out[DCF_SNAPSHOT_LEN];
        dcf_snapshot_unpack(GV_SNAPSHOT[i], &s);
        dcf_snapshot_pack(&s, out);
        if (memcmp(out, GV_SNAPSHOT[i], DCF_SNAPSHOT_LEN) != 0) fail("snapshot roundtrip", i);
    }
    printf("PASS: %d SNAPSHOT blocks unpack->pack losslessly\n", GV_N_SNAPSHOT);

    /* ── 4. INPUT body pack∘unpack is byte-lossless ── */
    for (int i = 0; i < GV_N_INPUT; i++) {
        dcf_input_t p;
        uint8_t out[DCF_INPUT_LEN];
        dcf_input_unpack(GV_INPUT[i], &p);
        dcf_input_pack(&p, out);
        if (memcmp(out, GV_INPUT[i], DCF_INPUT_LEN) != 0) fail("input roundtrip", i);
    }
    printf("PASS: %d INPUT blocks unpack->pack losslessly\n", GV_N_INPUT);

    if (failures == 0)
        printf("\nALL GAME VECTORS HOLD — C DCF-Game L2 is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C DCF-Game L2 is NOT cemented.\n", failures);
    return failures != 0;
}
