/* GENERATED by python/MCP/gen_pipemulti_vectors.py — DO NOT EDIT. */
#ifndef DCF_PIPEMULTI_VECTORS_GEN_H
#define DCF_PIPEMULTI_VECTORS_GEN_H
#include <stdint.h>

#define MCV_VERSION        1
#define MCV_PAYLOAD_LEN     4
#define MCV_MAGIC_MASK      0xC0
#define MCV_MAGIC           0xC0
#define MCV_MAX_COUNT       3

/* Opcodes (must match demod_pipemulti.h). */
#define MCV_OP_NOP            0
#define MCV_OP_CREDIT_DELTA   1
#define MCV_OP_ACK_CUMUL      2
#define MCV_OP_ACK_SELECTIVE  3
#define MCV_OP_NACK_ONE       4
#define MCV_OP_DONE_HINT      5
#define MCV_OP_ABORT_HINT     6
#define MCV_OP_RESERVED       7

typedef struct { const char *name; uint16_t count; uint8_t flags; uint8_t bytes[4]; uint8_t local_idx[3]; uint8_t opcode[3]; uint8_t param_lsb[3]; } mc_main_t;
static const mc_main_t MC_MAIN[] = {
  {"anchor_count1_NOP",1,0x00,{0xD0,0x00,0x00,0x00},{0,0,0},{0,0,0},{0,0,0}},
  {"count1_mixed",1,0x00,{0xD0,0x0C,0x00,0x00},{0,0,0},{1,0,0},{1,0,0}},
  {"count2_mixed",2,0x00,{0xE0,0x0C,0x90,0x00},{0,2,0},{1,2,0},{1,0,0}},
  {"count3_mixed",3,0x00,{0xF0,0x0C,0x90,0xF4},{0,2,3},{1,2,6},{1,0,1}},
  {"opcode_NOP",1,0x00,{0xD0,0x84,0x00,0x00},{2,0,0},{0,0,0},{1,0,0}},
  {"opcode_CREDIT_DELTA",1,0x00,{0xD0,0x8C,0x00,0x00},{2,0,0},{1,0,0},{1,0,0}},
  {"opcode_ACK_CUMUL",1,0x00,{0xD0,0x94,0x00,0x00},{2,0,0},{2,0,0},{1,0,0}},
  {"opcode_ACK_SELECTIVE",1,0x00,{0xD0,0x9C,0x00,0x00},{2,0,0},{3,0,0},{1,0,0}},
  {"opcode_NACK_ONE",1,0x00,{0xD0,0xA4,0x00,0x00},{2,0,0},{4,0,0},{1,0,0}},
  {"opcode_DONE_HINT",1,0x00,{0xD0,0xAC,0x00,0x00},{2,0,0},{5,0,0},{1,0,0}},
  {"opcode_ABORT_HINT",1,0x00,{0xD0,0xB4,0x00,0x00},{2,0,0},{6,0,0},{1,0,0}},
  {"param_credit_delta_lsb0",1,0x00,{0xD0,0x08,0x00,0x00},{0,0,0},{1,0,0},{0,0,0}},
  {"param_credit_delta_lsb1",1,0x00,{0xD0,0x0C,0x00,0x00},{0,0,0},{1,0,0},{1,0,0}},
  {"local_idx_0",1,0x00,{0xD0,0x18,0x00,0x00},{0,0,0},{3,0,0},{0,0,0}},
  {"local_idx_1",1,0x00,{0xD0,0x58,0x00,0x00},{1,0,0},{3,0,0},{0,0,0}},
  {"local_idx_2",1,0x00,{0xD0,0x98,0x00,0x00},{2,0,0},{3,0,0},{0,0,0}},
  {"local_idx_3",1,0x00,{0xD0,0xD8,0x00,0x00},{3,0,0},{3,0,0},{0,0,0}},
};
#define MC_N_MAIN (int)(sizeof(MC_MAIN)/sizeof(MC_MAIN[0]))

typedef struct { const char *name; uint8_t bytes[4]; int must_raise; } mc_reject_t;
static const mc_reject_t MC_REJECT[] = {
  {"pack_reserved_opcode_raises",{0xD0,0x38,0x00,0x00},1},
  {"unpack_count0_raises",{0xC0,0x00,0x00,0x00},1},
  {"unpack_bad_magic_raises",{0x40,0x00,0x00,0x00},1},
  {"unpack_nonzero_flags_raises",{0xD1,0x00,0x00,0x00},1},
  {"unpack_pad_bits_raises",{0xD0,0x01,0x00,0x00},1},
  {"unpack_unused_slot_nonzero_raises",{0xE0,0x0C,0x90,0x44},1},
};
#define MC_N_REJECT (int)(sizeof(MC_REJECT)/sizeof(MC_REJECT[0]))

typedef struct { const char *name; uint8_t byte0; int is_mc; int is_classic; } mc_discrim_t;
static const mc_discrim_t MC_DISCRIM[] = {
  {"anchor_count1_NOP",0xD0,1,0},
  {"count1_mixed",0xD0,1,0},
  {"count2_mixed",0xE0,1,0},
  {"count3_mixed",0xF0,1,0},
  {"opcode_NOP",0xD0,1,0},
  {"classic_open",0x00,0,1},
  {"classic_credit",0x01,0,1},
  {"classic_sack",0x02,0,1},
  {"classic_nack",0x03,0,1},
  {"classic_done",0x04,0,1},
  {"classic_abort",0x05,0,1},
  {"audio_ctrl_desc",0x7C,0,0},
};
#define MC_N_DISCRIM (int)(sizeof(MC_DISCRIM)/sizeof(MC_DISCRIM[0]))

#endif /* DCF_PIPEMULTI_VECTORS_GEN_H */
