#define EXS_NEED_FLOAT 0
/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>
#ifndef EXS_NEED_FLOAT
#define EXS_NEED_FLOAT 1
#endif
#if EXS_NEED_FLOAT
#include <float.h>
#endif

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

#if EXS_NEED_FLOAT
/* ---- IEEE binary32/64: the numeric subset's one target (spec 5.4) -------
 * ADR 0012's rung (b), spelled with <float.h> exactly as ADR 0012 names it
 * -- freestanding-safe, unlike __STDC_IEC_559__ (which a freestanding
 * implementation may define without honouring). `float` is binary32 and
 * `double` binary64, and no operation gains precision: FLT_EVAL_METHOD 0
 * is what makes `float op float` a FLOAT operation in C rather than a
 * double one (C's usual arithmetic conversions leave the type alone, but
 * only an evaluation method of 0 leaves the RESULT alone). Subnormals are
 * values (subnormales conservata); where C11's <float.h> stays silent
 * about them (the *_HAS_SUBNORM macros are optional before C23) the
 * runtime's MXCSR/FPCR image is what enforces it -- FTZ and DAZ clear,
 * which the reference prelude's 0x1F80 image also carries. */
_Static_assert(FLT_RADIX == 2, "exsecutor: the numeric subset is IEEE binary32/64 (spec 5.4)");
_Static_assert(FLT_MANT_DIG == 24 && DBL_MANT_DIG == 53,
               "exsecutor: float is binary32 and double is binary64");
_Static_assert(FLT_MAX_EXP == 128 && DBL_MAX_EXP == 1024,
               "exsecutor: binary32/64 exponent widths");
#if FLT_EVAL_METHOD != 0
# error "exsecutor: FLT_EVAL_METHOD must be 0 (spec 5.4: one rounding, in the operands' own width)"
#endif
#if defined(FLT_HAS_SUBNORM) && FLT_HAS_SUBNORM != 1
# error "exsecutor: float subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif
#if defined(DBL_HAS_SUBNORM) && DBL_HAS_SUBNORM != 1
# error "exsecutor: double subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif

/* Contraction (spec 5.4 contractio explicita; ADR 0012 problem 1). One IR
 * op is one C statement, so no emitted statement ever holds a
 * multiply-and-add tree to contract -- `fma` is the only contraction the
 * language has, it is refused by name in both backends, and this pragma is
 * the belt to that brace. `#pragma STDC FP_CONTRACT OFF` is NOT emitted:
 * measured to do nothing in both compilers, and GCC warns about it under
 * -Wall (c-backend.md D3, finding 12). Clang has nothing that works from
 * inside the source (`#pragma clang fp contract(off)` does not override a
 * command-line -ffp-contract=fast), so nothing is said to it and nothing
 * is lied about. */
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC optimize("fp-contract=off")
#endif
#endif /* EXS_NEED_FLOAT */

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

#if EXS_NEED_FLOAT
/* Floats from their bits -- `fconst`'s round-trip. `fconst F bits` carries
 * the RAW bit pattern (ssa-ir.md 2.3: bits, never decimal text) and it must
 * come back exactly: payload bits included (a NaN's payload survives fneg),
 * sign included (-0.0 is a different constant from 0.0), subnormal bits
 * included (subnormales conservata). A C floating literal cannot spell any
 * of that -- a hex floating literal for an out-of-range pattern loses the
 * NaN payload and the quiet bit -- so the pattern is written as an integer
 * constant and re-read through the object representation:
 * __builtin_memcpy, the GCC-recommended bit-cast, already measured and on
 * D3's extension list for `copy n` (c-backend.md finding 13). Assumes a
 * float's byte order is the integer byte order -- true of every target in
 * scope: x86_64, riscv64 and mips64 are each uniform in their byte order,
 * which is what the emitted `exsi_ld_n` selection also assumes. */
static inline float exsi_f32_from_bits(uint32_t b)
{ float f; __builtin_memcpy(&f, &b, sizeof f); return f; }
static inline double exsi_f64_from_bits(uint64_t b)
{ double d; __builtin_memcpy(&d, &b, sizeof d); return d; }

/* The way back, for `store F`: the float's bit pattern as the integer the
 * byte-store helpers carry. Same bit-cast, same assumption a few lines
 * above (a float's byte order is the integer byte order) -- the round trip
 * store-then-load is the identity on every --hospes row, which is all
 * memory consistency asks of a bit pattern with no numeric reading. */
static inline uint32_t exsi_bits_from_f32(float f)
{ uint32_t b; __builtin_memcpy(&b, &f, sizeof b); return b; }
static inline uint64_t exsi_bits_from_f64(double d)
{ uint64_t b; __builtin_memcpy(&b, &d, sizeof b); return b; }

/* The vector float group (spec 5.4's vf32.N/vf64.N; ssa-ir.md 2.2: N lanes
 * of binary32/binary64, N in {2,4,8}), as C's vector_size extension -- one
 * of the GCC/Clang extensions ADR 0012's set already carries. One IR
 * vadd/vsub/vmul/vdiv is one C statement on the whole vector (the one
 * op-per-statement rule), and the operator's elementwise lowering is the
 * ONE IEEE rounding per lane the reference's packed addps/addpd carries:
 * GCC and Clang both lower vector_size arithmetic elementwise on x86-64
 * and soft-lower it on the mips64-none cross target, which is what keeps
 * cross=yes alive for this wave. NO intrinsics and no <emmintrin.h>-family
 * header: those spellings do not exist on the cross target. */
typedef float exs_vf32_2 __attribute__((vector_size(8)));
typedef float exs_vf32_4 __attribute__((vector_size(16)));
typedef float exs_vf32_8 __attribute__((vector_size(32)));
typedef double exs_vf64_2 __attribute__((vector_size(16)));
typedef double exs_vf64_4 __attribute__((vector_size(32)));
typedef double exs_vf64_8 __attribute__((vector_size(64)));
/* The N = 8 helpers carry 32/64-byte vectors, and both compilers note at
 * their definitions (GCC) or call sites (Clang) that passing such a vector
 * without AVX enabled "changes the ABI" (-Wpsabi). That warning is a
 * statement about TWO translation units compiled with different -m flags
 * sharing a function boundary -- and no boundary here carries a vector:
 * the helpers are `static inline` inside the single emitted unit, and the
 * unit's one imported/exported symbol (exs_initium's unsigned char *) is a
 * scalar. The note is noise for this blob and is switched off for it, the
 * way -Wno-unused-function is for the rest of it (recorded, not hidden). */
#if defined(__clang__)
# pragma clang diagnostic ignored "-Wpsabi"
#elif defined(__GNUC__)
# pragma GCC diagnostic ignored "-Wpsabi"
#endif
_Static_assert(sizeof(exs_vf32_2) == 8 && sizeof(exs_vf32_4) == 16 &&
               sizeof(exs_vf32_8) == 32,
               "exsecutor: a vf32.N is N binary32 lanes, packed (spec 5.4)");
_Static_assert(sizeof(exs_vf64_2) == 16 && sizeof(exs_vf64_4) == 32 &&
               sizeof(exs_vf64_8) == 64,
               "exsecutor: a vf64.N is N binary64 lanes, packed (spec 5.4)");

/* A vector in memory is its lanes' raw IEEE images, back to back in
 * subscript order, each element in the target's byte order -- the same
 * assumption the scalar helpers above name, so the nativus round trip is
 * the identity on every --hospes row. The load/store helpers are memcpy
 * bit baggage exactly the way the scalar float path's from_bits/bits_from
 * helpers are: no lane is read numerically on the path, so a NaN payload,
 * -0.0's sign and a subnormal's bits survive every copy (subnormales
 * conservata). */
static inline exs_vf32_2 exsi_ld_vf32_2(const unsigned char *p)
{ exs_vf32_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_4 exsi_ld_vf32_4(const unsigned char *p)
{ exs_vf32_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_8 exsi_ld_vf32_8(const unsigned char *p)
{ exs_vf32_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_2 exsi_ld_vf64_2(const unsigned char *p)
{ exs_vf64_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_4 exsi_ld_vf64_4(const unsigned char *p)
{ exs_vf64_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_8 exsi_ld_vf64_8(const unsigned char *p)
{ exs_vf64_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline void exsi_st_vf32_2(unsigned char *p, exs_vf32_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_4(unsigned char *p, exs_vf32_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_8(unsigned char *p, exs_vf32_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_2(unsigned char *p, exs_vf64_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_4(unsigned char *p, exs_vf64_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_8(unsigned char *p, exs_vf64_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }

/* itof from a signed integer's canonical bits. The carrier holds an iN
 * sign-extended (ssa-ir.md 2.2), so the two's-complement value IS the bit
 * pattern -- but C leaves a uint64_t -> int64_t conversion that does not
 * fit IMPLEMENTATION-DEFINED, a fact this prologue asserts nowhere and
 * refuses to rely on, so the bits are re-read as int64_t exactly the way
 * fconst re-reads a pattern as a float. The signed type appears here and
 * nowhere else: this is a conversion into a float, not arithmetic, and the
 * one-op-per-statement rule keeps it out of any expression a compiler
 * could contract. */
static inline int64_t exsi_i64_from_bits(uint64_t b)
{ int64_t s; __builtin_memcpy(&s, &b, sizeof s); return s; }

#endif /* EXS_NEED_FLOAT */

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

/* div and rem -- spec 5.4 as decided 2026-09-25: the quotient TRUNCATED
 * TOWARD ZERO and the remainder's sign FOLLOWING THE DIVIDEND, so that
 * `a == (a/b)*b + (a rem b)` holds at every pair of signs. Both trap on a
 * zero divisor, and both trap on T_MIN / -1 -- `rem` included, whose
 * mathematical value there is 0: it is the remainder OF a division that
 * does not exist, and a `rem` answering 0 where its own `div` traps would
 * falsify the identity at the one pair of operands two instructions can
 * check it on. emit.inc's __bfa_emit_divrem argues the same two paragraphs
 * for the reference; these helpers are the same function, not a second
 * opinion about it.
 *
 * THE CHECKS PRECEDE THE DIVISION, where every other trapping helper above
 * checks after, and they have to for two independent reasons. The semantic
 * one: `rem`'s result carries no trace of the overflow (T_MIN rem -1 is 0,
 * a perfectly good value of T), so there is nothing to check afterwards.
 * The harness one: every fixture is compiled `-fsanitize=undefined
 * -fno-sanitize-recover=all`, so a helper that DIVIDED first would abort
 * inside UBSan -- wrong status, wrong text, exsrt_abortus never reached --
 * on precisely the two inputs whose trap is the thing being tested.
 *
 * T_MIN IS T'S OWN, NOT INT64_MIN. In `i8`, -128 / -1 is 128, which no
 * `i8` holds, and the 64-bit division of a sign-extended -128 by -1
 * computes it without a murmur; tests/ir/trap_div_minneg1.ir is that case
 * and nothing else. So the comparison is against -2^(N-1) for the operand
 * type's own N. At N = 64 the same line also stands in for the hardware's
 * divide error, which the reference likewise turns into kind 1 rather than
 * a second signal that depends on the width.
 *
 * NO SIGNED C DIVISION ANYWHERE. The signed pair divides MAGNITUDES and
 * puts the sign back, exactly as exsi_mul_i does, so the carrier's
 * implementation-defined uint64_t -> int64_t conversion is never needed
 * (this file relies on it nowhere but exsi_i64_from_bits, and then through
 * memcpy) and UBSan's signed-overflow check is never armed. `0 - x` on a
 * uint64_t is modular C, not overflow. The magnitude of T_MIN is 2^63,
 * which `0 - a` leaves as 2^63 -- still the right unsigned magnitude.
 *
 * NO NORMALISATION, and the proof rather than the habit. With a zero
 * divisor and T_MIN / -1 excluded the result is ALREADY a value of T:
 * |a/b| <= |a| for |b| >= 1, so the only out-of-range quotient is -T_MIN,
 * which is precisely the case just excluded; and |a rem b| < |b| <=
 * 2^(N-1), in range at every sign. `0 - q` on an in-range magnitude leaves
 * the value sign-extended, which is the canonical form (ssa-ir.md 2.2).
 *
 * n IS UNUSED IN THE UNSIGNED PAIR and the parameter still stays. A uN
 * quotient is at most the dividend and a uN remainder is less than the
 * divisor, so neither can leave the type, and unsigned division has no
 * T_MIN case to exclude -- but the emitter writes ONE call shape for every
 * row of the helper table, so the argument is passed and discarded the way
 * exsi_subs_u discards it. */
static inline uint64_t exsi_div_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a / b; }
static inline uint64_t exsi_rem_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a % b; }
static inline uint64_t exsi_div_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
    uint64_t q = ma / mb;
    return (sa ^ sb) ? 0 - q : q; } }                    /* canonical by construction */
static inline uint64_t exsi_rem_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;
    uint64_t r = ma % mb;
    return sa ? 0 - r : r; } }                           /* the DIVIDEND's sign */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 8, "exsecutor: this hospes has 64-bit addresses");

uint64_t exs_redundantia(unsigned char *p0, uint64_t p1);
uint64_t exs_syndroma(unsigned char *p0);
void exs_obsigna(unsigned char *p0, unsigned char *p1);
void exs_vacuum(unsigned char *p0);
uint64_t exs_lege(unsigned char *p0);
uint64_t exs_redundantia_sarcinae(unsigned char *p0, uint64_t p1);
uint64_t exs_admitte(unsigned char *p0, uint64_t p1);

uint64_t exs_redundantia(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    unsigned char *v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t v42;
    uint64_t v43;
    uint64_t t6;
    uint64_t t9;
    uint64_t t21;
    uint64_t t24;
    uint64_t t40;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(65535);
    v4 = UINT64_C(0);
    t9 = v3;
    t6 = v4;
    v9 = t9;
    v6 = t6;
    goto b2;
b2:
    v7 = (v6 < v2);
    if (v7) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = UINT64_C(17);
    if (v6 >= v10) exsrt_abortus(1);
    v12 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v6 * 1);
    v13 = exsi_norm_u(exsi_ld_n(v12 + 0, 1), 8);
    v14 = exsi_norm_u(exsi_norm_u(v13, 8), 16);
    v15 = UINT64_C(8);
    v16 = exsi_shl_u(v14, v15, 16);
    v17 = v9 ^ v16;
    v18 = UINT64_C(0);
    v19 = UINT64_C(8);
    t24 = v17;
    t21 = v18;
    v24 = t24;
    v21 = t21;
    goto b6;
b4:
    return v9;
b5:
    v42 = UINT64_C(1);
    v43 = v6 + v42;
    t9 = v24;
    t6 = v43;
    v9 = t9;
    v6 = t6;
    goto b2;
b6:
    v22 = (v21 < v19);
    if (v22) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v25 = UINT64_C(32768);
    v26 = (v24 >= v25);
    if (v26) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    goto b5;
b9:
    v37 = UINT64_C(1);
    v38 = v21 + v37;
    t24 = v40;
    t21 = v38;
    v24 = t24;
    v21 = t21;
    goto b6;
b10:
    v28 = UINT64_C(1);
    v29 = exsi_shl_u(v24, v28, 16);
    v30 = UINT64_C(4129);
    v31 = v29 ^ v30;
    t40 = v31;
    v40 = t40;
    goto b12;
b11:
    v33 = UINT64_C(1);
    v34 = exsi_shl_u(v24, v33, 16);
    t40 = v34;
    v40 = t40;
    goto b12;
b12:
    goto b9;
}

uint64_t exs_syndroma(unsigned char *p0)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    _Alignas(1) unsigned char s2[17];
    v1 = p0;
    v2 = s2;
    __builtin_memcpy(v2, v1, 17);
    v4 = UINT64_C(15);
    v5 = exs_redundantia(v1, v4);
    v6 = exsi_norm_u(exsi_ld_be(v2 + 15, 2), 16);
    v7 = v5 ^ v6;
    return v7;
}

void exs_obsigna(unsigned char *p0, unsigned char *p1)
{
    unsigned char *v1;
    unsigned char *v2;
    unsigned char *v3;
    uint64_t v5;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    _Alignas(1) unsigned char s3[17];
    v1 = p0;
    v2 = p1;
    v3 = s3;
    __builtin_memcpy(v3, v2, 17);
    v5 = UINT64_C(211);
    exsi_st_n(v3 + 0, 1, v5);
    v7 = UINT64_C(1);
    v3[1] = (unsigned char)(((unsigned)v3[1] & ~(15u << 4)) | (((unsigned)v7 & 15u) << 4));
    v9 = UINT64_C(15);
    v10 = exs_redundantia(v3, v9);
    exsi_st_be(v3 + 15, 2, v10);
    __builtin_memcpy(v1, v3, 17);
    return;
}

void exs_vacuum(unsigned char *p0)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    v1 = p0;
    v2 = UINT64_C(0);
    v3 = UINT64_C(0);
    v4 = UINT64_C(0);
    v5 = UINT64_C(0);
    v6 = UINT64_C(0);
    v7 = UINT64_C(0);
    v8 = UINT64_C(0);
    v9 = UINT64_C(0);
    v10 = UINT64_C(0);
    exsi_st_n(v1 + 0, 1, v2);
    v1[1] = (unsigned char)(((unsigned)v1[1] & ~(15u << 4)) | (((unsigned)v3 & 15u) << 4));
    v1[1] = (unsigned char)(((unsigned)v1[1] & ~(15u << 0)) | (((unsigned)v4 & 15u) << 0));
    exsi_st_be(v1 + 2, 2, v5);
    exsi_st_be(v1 + 4, 2, v6);
    exsi_st_be(v1 + 6, 2, v7);
    exsi_st_be(v1 + 8, 4, v8);
    exsi_st_be(v1 + 12, 3, v9);
    exsi_st_be(v1 + 15, 2, v10);
    return;
}

uint64_t exs_lege(unsigned char *p0)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v22;
    _Alignas(1) unsigned char s2[17];
    v1 = p0;
    v2 = s2;
    __builtin_memcpy(v2, v1, 17);
    v4 = exsi_norm_u(exsi_ld_n(v2 + 0, 1), 8);
    v5 = UINT64_C(211);
    v6 = (v4 != v5);
    if (v6) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v8 = UINT64_C(1);
    return v8;
b3:
    v10 = (((unsigned)v2[1] >> 4) & 15u);
    v11 = UINT64_C(1);
    v12 = (v10 != v11);
    if (v12) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v14 = UINT64_C(2);
    return v14;
b5:
    v16 = exs_syndroma(v1);
    v17 = UINT64_C(0);
    v18 = (v16 != v17);
    if (v18) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v20 = UINT64_C(3);
    return v20;
b7:
    v22 = UINT64_C(0);
    return v22;
}

uint64_t exs_redundantia_sarcinae(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    unsigned char *v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t v42;
    uint64_t v43;
    uint64_t t6;
    uint64_t t9;
    uint64_t t21;
    uint64_t t24;
    uint64_t t40;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(65535);
    v4 = UINT64_C(0);
    t9 = v3;
    t6 = v4;
    v9 = t9;
    v6 = t6;
    goto b2;
b2:
    v7 = (v6 < v2);
    if (v7) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = UINT64_C(32);
    if (v6 >= v10) exsrt_abortus(1);
    v12 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v6 * 1);
    v13 = exsi_norm_u(exsi_ld_n(v12 + 0, 1), 8);
    v14 = exsi_norm_u(exsi_norm_u(v13, 8), 16);
    v15 = UINT64_C(8);
    v16 = exsi_shl_u(v14, v15, 16);
    v17 = v9 ^ v16;
    v18 = UINT64_C(0);
    v19 = UINT64_C(8);
    t24 = v17;
    t21 = v18;
    v24 = t24;
    v21 = t21;
    goto b6;
b4:
    return v9;
b5:
    v42 = UINT64_C(1);
    v43 = v6 + v42;
    t9 = v24;
    t6 = v43;
    v9 = t9;
    v6 = t6;
    goto b2;
b6:
    v22 = (v21 < v19);
    if (v22) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v25 = UINT64_C(32768);
    v26 = (v24 >= v25);
    if (v26) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    goto b5;
b9:
    v37 = UINT64_C(1);
    v38 = v21 + v37;
    t24 = v40;
    t21 = v38;
    v24 = t24;
    v21 = t21;
    goto b6;
b10:
    v28 = UINT64_C(1);
    v29 = exsi_shl_u(v24, v28, 16);
    v30 = UINT64_C(4129);
    v31 = v29 ^ v30;
    t40 = v31;
    v40 = t40;
    goto b12;
b11:
    v33 = UINT64_C(1);
    v34 = exsi_shl_u(v24, v33, 16);
    t40 = v34;
    v40 = t40;
    goto b12;
b12:
    goto b9;
}

uint64_t exs_admitte(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    unsigned char *v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    unsigned char *v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    uint64_t v23;
    uint64_t v25;
    unsigned char *v27;
    uint64_t v28;
    uint64_t v29;
    unsigned char *v31;
    uint64_t v34;
    uint64_t v35;
    uint64_t v37;
    uint64_t v39;
    uint64_t v40;
    unsigned char *v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v48;
    uint64_t v50;
    uint64_t v51;
    uint64_t v52;
    uint64_t v54;
    uint64_t v56;
    uint64_t v57;
    uint64_t v58;
    uint64_t v60;
    uint64_t v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v65;
    uint64_t v66;
    uint64_t v67;
    uint64_t v69;
    uint64_t v71;
    uint64_t v72;
    uint64_t v73;
    uint64_t v75;
    uint64_t v77;
    uint64_t v78;
    uint64_t v79;
    uint64_t v81;
    uint64_t v83;
    uint64_t v85;
    uint64_t t10;
    uint64_t t22;
    _Alignas(1) unsigned char s6[17];
    _Alignas(1) unsigned char s42[32];
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(17);
    v4 = (v2 == v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = s6;
    v7 = UINT64_C(0);
    v8 = UINT64_C(0);
    t10 = v8;
    v10 = t10;
    goto b4;
b3:
    v39 = UINT64_C(32);
    v40 = (v2 == v39);
    if (v40) {
        goto b11;
    } else {
        goto b12;
    }
b4:
    v11 = UINT64_C(17);
    v12 = (v10 < v11);
    if (v12) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v14 = (unsigned char *)((uintptr_t)v6 + (uintptr_t)v10 * 1);
    exsi_st_n(v14 + 0, 1, v7);
    v16 = UINT64_C(1);
    v17 = v10 + v16;
    t10 = v17;
    v10 = t10;
    goto b4;
b6:
    v19 = UINT64_C(0);
    v20 = UINT64_C(17);
    t22 = v19;
    v22 = t22;
    goto b7;
b7:
    v23 = (v22 < v20);
    if (v23) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v25 = UINT64_C(32);
    if (v22 >= v25) exsrt_abortus(1);
    v27 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v22 * 1);
    v28 = exsi_norm_u(exsi_ld_n(v27 + 0, 1), 8);
    v29 = UINT64_C(17);
    if (v22 >= v29) exsrt_abortus(1);
    v31 = (unsigned char *)((uintptr_t)v6 + (uintptr_t)v22 * 1);
    exsi_st_n(v31 + 0, 1, v28);
    goto b10;
b9:
    v37 = exs_lege(v6);
    return v37;
b10:
    v34 = UINT64_C(1);
    v35 = v22 + v34;
    t22 = v35;
    v22 = t22;
    goto b7;
b11:
    v42 = s42;
    __builtin_memcpy(v42, v1, 32);
    v44 = exsi_norm_u(exsi_ld_n(v42 + 0, 1), 8);
    v45 = UINT64_C(211);
    v46 = (v44 != v45);
    if (v46) {
        goto b13;
    } else {
        goto b14;
    }
b12:
    v85 = UINT64_C(6);
    return v85;
b13:
    v48 = UINT64_C(1);
    return v48;
b14:
    v50 = (((unsigned)v42[1] >> 4) & 15u);
    v51 = UINT64_C(1);
    v52 = (v50 != v51);
    if (v52) {
        goto b15;
    } else {
        goto b16;
    }
b15:
    v54 = UINT64_C(2);
    return v54;
b16:
    v56 = (((unsigned)v42[1] >> 0) & 15u);
    v57 = UINT64_C(5);
    v58 = (v56 != v57);
    if (v58) {
        goto b17;
    } else {
        goto b18;
    }
b17:
    v60 = UINT64_C(4);
    return v60;
b18:
    v62 = UINT64_C(30);
    v63 = exs_redundantia_sarcinae(v1, v62);
    v64 = exsi_norm_u(exsi_ld_be(v42 + 30, 2), 16);
    v65 = v63 ^ v64;
    v66 = UINT64_C(0);
    v67 = (v65 != v66);
    if (v67) {
        goto b19;
    } else {
        goto b20;
    }
b19:
    v69 = UINT64_C(3);
    return v69;
b20:
    v71 = (((unsigned)v42[2] >> 4) & 15u);
    v72 = UINT64_C(1);
    v73 = (v71 != v72);
    if (v73) {
        goto b21;
    } else {
        goto b22;
    }
b21:
    v75 = UINT64_C(5);
    return v75;
b22:
    v77 = (((unsigned)v42[16] >> 4) & 15u);
    v78 = UINT64_C(1);
    v79 = (v77 != v78);
    if (v79) {
        goto b23;
    } else {
        goto b24;
    }
b23:
    v81 = UINT64_C(5);
    return v81;
b24:
    v83 = UINT64_C(0);
    return v83;
}

